### ISSUE TITLE
Can't download album with long names

### ISSUE THREAD

**Issue by jinoo2005609** [Slyyxp/rsack#43]
Can't download album with long names in genie.
For example : [Genie](https://www.genie.co.kr/detail/albumInfo?axnm=82485782)

**Comment by Slyyxp** [comment]
I will write something to downsize the filename later today.

**Comment by Slyyxp** [comment]
Fixed with 3a563b59c7a20cd74d47da6c3cbaf8b5ed6c360d

I see no way to handle the rename without removing the track title entirely.

There are too many variables, you could split at & and other such characters but that would be inconsistent. You coulda also remove just enough characters from the end that it doesn't error.

Doing either of these things would result in an incoherent track title, so it has just been removed and they can be renamed manually at the downloaders leisure.
