### ISSUE TITLE
Pass Preview Tracks

### ISSUE THREAD

**Issue by zyndin** [Slyyxp/rsack#64]
Hello,

I can not download this album with lastest version.

https://music.bugs.co.kr/album/20063779?wl_ref=list_tr_11_search

Thank you for your effort

**Comment by Slyyxp** [comment]
Only format available is AAC.
AAC is not supported since I haven't actually seen a case like this with Bugs so far.

I will write code to support this at some point.

**Comment by Slyyxp** [comment]
I am changing the parameters of this issue.

- 이 앨범의 수록곡 중 일부 곡은 권리사의 요청으로 재생할 수 없습니다. (1분 미리듣기만 할 수 있음).

7/8 tracks are provided as 60 second previews in AAC format. I have no intention to support these files since they are incomplete tracks.

I will add something that catches these files and passes.
